kind: pipeline
type: docker
name: s3-proxy

clone:
  disable: true

steps:
- name: clone
  image: smasherofallthings/debug
  commands:
  - GIT_SSL_NO_VERIFY=true git clone -v $DRONE_GIT_HTTP_URL .
  - GIT_SSL_NO_VERIFY=true git checkout $DRONE_COMMIT

- name: Docker Image
  image: smasherofallthings/python-fe
  commands:
  - npm install
  - npm run solid && npm run tailwind
  - docker build -t smasherofallthings/s3proxy . && docker push smasherofallthings/s3proxy
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: docker-creds
    path: /root/.docker/config.json

- name: Push repo to public repos
  image: smasherofallthings/debug
  commands:
  - git checkout $DRONE_BRANCH
  - git remote add github https://github.com/smashthings/s3proxy.git
  - git push -u github
  - git remote add gitlab https://gitlab.com/scripteddog/s3proxy.git
  - git push -u gitlab

volumes:
- name: docker-socket
  host:
    path: /var/run/docker.sock
- name: docker-creds
  host:
    path: /root/.docker/config.json

trigger:
  branch:
    - master
    - pipeline
  event:
    - push

