version: '3.1'

services:
  dev:
    image: smasherofallthings/python-fe
    restart: "no"
    network_mode: host
    environment:
      HOME: /interactive
      PYTHONUNBUFFERED: "true"
    entrypoint:
      - npm
      - run
      - watch
    volumes:
      - .:/interactive
    working_dir: "/interactive"

  prod:
    image: smasherofallthings/s3proxy:latest
    ports:
      - 3000:3000
    build:
      context: '.'
      dockerfile: Dockerfile
      args:
        BASEIMAGE: smasherofallthings/flask-waitress
        FE_BUILD: smasherofallthings/python-fe
