version: '3.1'

services:
  s3proxy:
    image: smasherofallthings/s3proxy:latest
    restart: "no"
    network_mode: host
    environment:
      PYTHONUNBUFFERED: "true"
      S3PROXYHEADER_Access_Control_Max_Age: "86400"
      S3PROXYHEADER_Access_Control_Allow_Origin: "*"
      S3PROXYHEADER_Access_Control_Allow_Methods: "GET,HEAD,OPTIONS"

      TARGET_BUCKET: "PUT_THE_NAME_OF_YOUR_BUCKET_HERE"
      AWS_ACCESS_KEY_ID: "PUT_YOUR_AWS_KEY_ID_HERE"
      AWS_SECRET_ACCESS_KEY: "PUT_YOUR_AWS_SECRET_KEY_HERE"